### ISSUE TITLE
getLeaguePositionsForSummoner empty response from Riot as a Fatal error 

### ISSUE THREAD

**Issue by cohenu** [dolejska-daniel/riot-api#43]
**Describe the bug**
empty response from `getLeaguePositionsForSummoner` causing the following error:
```html
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to RiotAPI\LeagueAPI\LeagueAPI::RiotAPI\LeagueAPI\{closure}() must be of the type array, null given, called in /var/www/[redacted]/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php on line 987 and defined in /var/www/[redacted]/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php:1558
Stack trace:
#0 /var/www/[redacted]/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php(987): RiotAPI\LeagueAPI\LeagueAPI-&gt;RiotAPI\LeagueAPI\{closure}(NULL)
#1 /var/www/[redacted]/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php(1564): RiotAPI\LeagueAPI\LeagueAPI-&gt;resolveOrEnqueuePromise(Object(GuzzleHttp\Promise\Promise), Object(Closure))
#2 /var/www/[redacted]/public_html/api/v1/rank/get.php(12): RiotAPI\LeagueAPI\LeagueAPI-&gt;getLeaguePositionsForSummoner('TXsHzGHq4CIqswg...')
#3 {main}
  thrown in <b>/var/www/[redacted]/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php</b> on line <b>1558</b><br />
```

**To Reproduce**
1. Initialize an instance of `LeagueAPI`
2. Make a requests using `getLeaguePositionsForSummoner` to unranked summoner

**Expected behavior**
The library should return an empty response.

**Screenshots**
Not relevant

**Server (please complete the following information):**
 - PHP version: 7.2.13

**Comment by dolejska-daniel** [comment]
Empty array was interpreted as `false` and therefore `null` has been saved as output. Fixed by removing the check since it is not really necessary anyway.
