### ISSUE TITLE
Tournament "Request is invalid."

### ISSUE THREAD

**Issue by FlorianMifsud** [dolejska-daniel/riot-api#68]
**Describe the bug**
Tournament error "Request is invalid."

**Server (please complete the following information):**
PHP 7.4.2 (cli) (built: Feb  1 2020 17:49:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

**Additional context**
function createTournamentProvider_STUB works
createTournamentProvider error

`PHP Fatal error:  Uncaught RiotAPI\\LeagueAPI\\Exceptions\\RequestException: LeagueAPI: Request is invalid. Bad request - Invalid URL in /var/www/html/L2P/php/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php:1242\nStack trace:\n#0 /var/www/html/L2P/php/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php(1174): RiotAPI\\LeagueAPI\\LeagueAPI->processCallResult()\n#1 /var/www/html/L2P/php/vendor/guzzlehttp/promises/src/Promise.php(203): RiotAPI\\LeagueAPI\\LeagueAPI->RiotAPI\\LeagueAPI\\{closure}()\n#2 /var/www/html/L2P/php/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler()\n#3 /var/www/html/L2P/php/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /var/www/html/L2P/php/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\\Promise\\TaskQueue->run()\n#5 /var/www/html/L2P/php/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\\Handler\\CurlMultiHandler->tick()\n#6 /var/www/html/L2P/php/v in /var/www/html/L2P/php/vendor/dolejska-daniel/riot-api/src/LeagueAPI/LeagueAPI.php on line 1242`

**Comment by FlorianMifsud** [comment]
Ok, my tld is .lol `Domain Restrictions
Only valid gTLDs approved by ICANN before March 2011 are considered valid. This excludes newer gTLDs such as (.mail, .xxx, .xyz, etc.)

Valid gTLDs (approved before March 2011)
aero, asia, biz, cat, com, coop, info, jobs, mobi, museum, name, net, org, pro, tel, travel, gov, edu, mil, int

Valid Country Code TLDs
ac, ad, ae, af, ag, ai, al, am, an, ao, aq, ar, as, at, au, aw, ax, az, ba, bb, bd, be, bf, bg, bh, bi, bj, bm, bn, bo, br, bs, bt, bv, bw, by, bz, ca, cc, cd, cf, cg, ch, ci, ck, cl, cm, cn, co, cr, cu, cv, cx, cy, cz, de, dj, dk, dm, do, dz, ec, ee, eg, er, es, et, eu, fi, fj, fk, fm, fo, fr, ga, gb, gd, ge, gf, gg, gh, gi, gl, gm, gn, gp, gq, gr, gs, gt, gu, gw, gy, hk, hm, hn, hr, ht, hu, id, ie, il, im, in, io, iq, ir, is, it, je, jm, jo, jp, ke, kg, kh, ki, km, kn, kp, kr, kw, ky, kz, la, lb, lc, li, lk, lr, ls, lt, lu, lv, ly, ma, mc, md, me, mg, mh, mk, ml, mm, mn, mo, mp, mq, mr, ms, mt, mu, mv, mw, mx, my, mz, na, nc, ne, nf, ng, ni, nl, no, np, nr, nu, nz, om, pa, pe, pf, pg, ph, pk, pl, pm, pn, pr, ps, pt, pw, py, qa, re, ro, rs, ru, rw, sa, sb, sc, sd, se, sg, sh, si, sj, sk, sl, sm, sn, so, sr, st, su, sv, sy, sz, tc, td, tf, tg, th, tj, tk, tl, tm, tn, to, tp, tr, tt, tv, tw, tz, ua, ug, uk, um, us, uy, uz, va, vc, ve, vg, vi, vn, vu, wf, ws, ye, yt, yu, za, zm, zw`
